"use client";
import {useEffect,useMemo,useState} from "react";
type Task={id:string,title:string,done:boolean,priority:"high"|"medium"|"low",area:string,date?:string,star?:boolean};
type Routine={id:string,title:string,part:"Morning"|"Afternoon"|"Evening",done:boolean,streak:number};
type Note={id:string,text:string,created:string};
const seed={tasks:[{id:"1",title:"Try Quick Capture",done:false,priority:"high" as const,area:"Personal",date:new Date().toISOString().slice(0,10)},{id:"2",title:"Star a task to keep it in focus",done:false,priority:"medium" as const,area:"Personal"}],routines:[{id:"r1",title:"Check daily plan",part:"Morning" as const,done:false,streak:0}],notes:[{id:"n1",text:"Resurfacing brings one saved thought back every day.",created:new Date().toISOString()}],areas:["Personal","School","Work","Travel"],inbox:[] as string[]};
const weight={high:3,medium:2,low:1};
export default function OrganizerApp(){
 const [data,setData]=useState(seed); const [ready,setReady]=useState(false); const [page,setPage]=useState("Today"); const [capture,setCapture]=useState(""); const [toast,setToast]=useState("");
 useEffect(()=>{try{const x=localStorage.getItem("operations-v1");if(x)setData(JSON.parse(x))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("operations-v1",JSON.stringify(data))},[data,ready]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.altKey&&e.key.toLowerCase()==="j"){e.preventDefault();(document.querySelector("#capture") as HTMLInputElement)?.focus()}};addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[]);
 const open=useMemo(()=>data.tasks.filter(t=>!t.done).sort((a,b)=>(Number(b.star)-Number(a.star))||weight[b.priority]-weight[a.priority]),[data.tasks]);
 const top=open.slice(0,3); const today=new Date().toISOString().slice(0,10);
 function addCapture(){const raw=capture.trim();if(!raw)return;const l=raw.toLowerCase();const isNote=/^(note|notitie|noteer|idee|onthoud|quote)/.test(l);const taskish=/huiswerk|leren|maken|print|sturen|bellen|taak|to.?do|moet|toets|presentatie|inlever/.test(l);
   if(isNote){setData(d=>({...d,notes:[{id:crypto.randomUUID(),text:raw.replace(/^(note|notitie|noteer|idee|onthoud|quote)[: -]*/i,""),created:new Date().toISOString()},...d.notes]}));setToast("Saved as note");}
   else if(taskish){let area=data.areas.find(a=>l.includes(a.toLowerCase()))||"Personal";let priority:"high"|"medium"|"low"=/high|hoog|urgent/.test(l)?"high":/low|laag/.test(l)?"low":"medium";let date=l.includes("vandaag")?today:undefined;let title=raw.replace(/\b(vandaag|high|hoog|urgent|medium|low|laag|personal|school|work|travel)\b/gi,"").replace(/\s+/g," ").trim();setData(d=>({...d,tasks:[{id:crypto.randomUUID(),title,done:false,priority,area,date},...d.tasks]}));setToast("Task saved");}
   else {setData(d=>({...d,inbox:[raw,...d.inbox]}));setToast("Sent to Needs Review");}
   setCapture("");setTimeout(()=>setToast(""),2200);
 }
 function toggle(id:string){setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,done:!t.done}:t)}))}
 function star(id:string){setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,star:!t.star}:t)}))}
 function TaskRow({t}:{t:Task}){return <div className={"task "+(t.done?"done":"")}><button className="check" onClick={()=>toggle(t.id)}>{t.done?"✓":""}</button><div><b>{t.title}</b><small>{t.area} · {t.priority}{t.date?" · "+t.date:" · Unscheduled"}</small></div><button className={"star "+(t.star?"on":"")} onClick={()=>star(t.id)}>★</button></div>}
 if(!ready)return <main className="loading">Operations</main>;
 const nav=["Today","Inbox","Tasks","Routines","Projects","Areas","Notes","Resurfacing","People","Search","Settings"];
 return <div className="shell"><aside><div className="brand">Operations<small>PERSONAL OS</small></div>{nav.map(n=><button key={n} className={page===n?"active":""} onClick={()=>setPage(n)}>{n}{n==="Inbox"&&data.inbox.length>0?<em>{data.inbox.length}</em>:null}</button>)}<div className="hint">ALT + J · QUICK CAPTURE</div></aside><main><header><span>{new Intl.DateTimeFormat("nl-NL",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</span><button onClick={()=>setPage("Inbox")}>Needs Review {data.inbox.length}</button></header>
 {page==="Today"&&<><Title kicker="OVERVIEW" title="Today" aside={open.length+" open tasks"}/><Capture/><Section title="Top 3"><div className="list">{top.map(t=><TaskRow key={t.id} t={t}/>)}</div></Section><div className="grid"><section><Section title="Next up"><div className="list">{open.slice(3,8).map(t=><TaskRow key={t.id} t={t}/>)}</div></Section></section><section><Section title="Resurfacing"><div className="quote">{data.notes[0]?.text||"Save a note and it will return here later."}</div></Section></section></div></>}
 {page==="Inbox"&&<><Title kicker="CAPTURE" title="Needs Review" aside="Nothing gets lost"/><Capture/><div className="list">{data.inbox.length?data.inbox.map((x,i)=><div className="review" key={i}><div><b>{x}</b><small>Needs a destination or more context</small></div><button onClick={()=>{setCapture(x);setData(d=>({...d,inbox:d.inbox.filter((_,j)=>j!==i)}))}}>Process</button></div>):<Empty text="Inbox zero. Nice."/ >}</div></>}
 {page==="Tasks"&&<><Title kicker="TASKS" title="Tasks" aside={data.tasks.length+" total"}/><Capture/><Section title="Open">{open.map(t=><TaskRow key={t.id} t={t}/>)}</Section><Section title="Completed">{data.tasks.filter(t=>t.done).map(t=><TaskRow key={t.id} t={t}/>)}</Section></>}
 {page==="Routines"&&<><Title kicker="ROUTINES" title="Daily habits" aside="streaks"/><div className="score"><strong>{Math.round(data.routines.filter(r=>r.done).length/Math.max(1,data.routines.length)*100)}%</strong><span>DAILY COMPLETION RATE</span></div>{["Morning","Afternoon","Evening"].map(part=><Section key={part} title={part}>{data.routines.filter(r=>r.part===part).map(r=><div className="routine" key={r.id}><button className="check" onClick={()=>setData(d=>({...d,routines:d.routines.map(x=>x.id===r.id?{...x,done:!x.done,streak:x.done?Math.max(0,x.streak-1):x.streak+1}:x)}))}>{r.done?"✓":""}</button><b>{r.title}</b><span>{"▪".repeat(Math.min(18,r.streak||1))} 🔥 {r.streak}</span></div>)}</Section>)}</>}
 {page==="Areas"&&<><Title kicker="SYSTEM" title="Areas" aside="editable"/><div className="cards">{data.areas.map(a=><div className="card" key={a}><i/> <b>{a}</b></div>)}<button className="addcard" onClick={()=>{const x=prompt("New area name");if(x&&!data.areas.includes(x))setData(d=>({...d,areas:[...d.areas,x]}))}}>＋ Add area</button></div></>}
 {page==="Notes"&&<><Title kicker="LIBRARY" title="Notes" aside={data.notes.length+" saved"}/><Capture/><div className="cards">{data.notes.map(n=><div className="notecard" key={n.id}><p>{n.text}</p><small>{new Date(n.created).toLocaleDateString("nl-NL")}</small></div>)}</div></>}
 {page==="Resurfacing"&&<><Title kicker="LIBRARY" title="Resurfacing" aside="one thought a day"/><div className="heroquote">“{data.notes[new Date().getDate()%Math.max(1,data.notes.length)]?.text||"Nothing saved yet."}”</div></>}
 {["Projects","People","Search"].includes(page)&&<><Title kicker="COMING NEXT" title={page} aside="v0.2"/><Empty text={"The "+page+" module is next in the build queue."}/></>}
 {page==="Settings"&&<><Title kicker="SYSTEM" title="Settings" aside="local-first"/><div className="settings"><b>Storage</b><span>On this device · free</span><button onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="operations-backup.json";a.click()}}>Export backup</button></div></>}
 </main>{toast&&<div className="toast">{toast}</div>}</div>;
 function Capture(){return <div className="capture"><input id="capture" value={capture} onChange={e=>setCapture(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addCapture()} placeholder="Capture anything… e.g. maandag Duits huiswerk high school"/><button onClick={addCapture}>Add</button></div>}
}
function Title({kicker,title,aside}:{kicker:string,title:string,aside:string}){return <div className="title"><div><small>{kicker}</small><h1>{title}</h1></div><span>{aside}</span></div>}
function Section({title,children}:{title:string,children:any}){return <section><div className="sectiontitle">{title}</div>{children}</section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
