"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Priority="high"|"medium"|"low";
type Task={id:string,title:string,done:boolean,priority:Priority,area:string,date?:string,star?:boolean};
type Routine={id:string,title:string,part:"Morning"|"Afternoon"|"Evening",done:boolean,streak:number};
type Note={id:string,text:string,created:string};
type Project={id:string,title:string,area:string,description:string,done:boolean};
type Person={id:string,name:string,birthday:string,notes:string};
type AppState={tasks:Task[];routines:Routine[];notes:Note[];areas:string[];inbox:string[];projects:Project[];people:Person[]};
const seed:AppState={tasks:[],routines:[],notes:[],areas:["Personal","School","Work","Travel"],inbox:[],projects:[],people:[]};
const weight={high:3,medium:2,low:1};
const uid=()=>crypto.randomUUID();
export default function OrganizerApp(){
 const [data,setData]=useState<AppState>(seed),[ready,setReady]=useState(false),[page,setPage]=useState("Today"),[toast,setToast]=useState("");
 const [composer,setComposer]=useState<null|"task"|"note"|"routine"|"project"|"person">(null),[processing,setProcessing]=useState<number|null>(null),[search,setSearch]=useState("");
 const [draft,setDraft]=useState({title:"",text:"",area:"Personal",priority:"medium" as Priority,date:"",part:"Morning" as Routine["part"],description:"",birthday:""});
 const inputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const x=localStorage.getItem("operations-v1");if(x){const p=JSON.parse(x);setData({...seed,...p,projects:p.projects||[],people:p.people||[]})}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("operations-v1",JSON.stringify(data))},[data,ready]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.altKey&&e.key.toLowerCase()==="j"){e.preventDefault();openComposer("task")}};addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[]);
 useEffect(()=>{if(composer)setTimeout(()=>inputRef.current?.focus(),30)},[composer]);
 const open=useMemo(()=>data.tasks.filter(t=>!t.done).sort((a,b)=>(Number(b.star)-Number(a.star))||weight[b.priority]-weight[a.priority]),[data.tasks]);
 const today=new Date().toISOString().slice(0,10),dateLabel=new Intl.DateTimeFormat("nl-NL",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
 const reset=()=>setDraft({title:"",text:"",area:data.areas[0]||"Personal",priority:"medium",date:"",part:"Morning",description:"",birthday:""});
 function openComposer(x:typeof composer){reset();setComposer(x)}
 function flash(x:string){setToast(x);setTimeout(()=>setToast(""),1800)}
 function saveTask(toInbox=false){const title=draft.title.trim();if(!title)return;if(toInbox){setData(d=>({...d,inbox:[title,...d.inbox]}));flash("Naar Inbox");}else{setData(d=>({...d,tasks:[{id:uid(),title,done:false,priority:draft.priority,area:draft.area,date:draft.date||undefined},...d.tasks]}));flash("Taak ingepland");}setComposer(null);setProcessing(null)}
 function saveNote(){if(!draft.text.trim())return;setData(d=>({...d,notes:[{id:uid(),text:draft.text.trim(),created:new Date().toISOString()},...d.notes]}));setComposer(null);flash("Notitie opgeslagen")}
 function saveRoutine(){if(!draft.title.trim())return;setData(d=>({...d,routines:[...d.routines,{id:uid(),title:draft.title.trim(),part:draft.part,done:false,streak:0}]}));setComposer(null);flash("Routine toegevoegd")}
 function saveProject(){if(!draft.title.trim())return;setData(d=>({...d,projects:[{id:uid(),title:draft.title.trim(),area:draft.area,description:draft.description,done:false},...d.projects]}));setComposer(null);flash("Project toegevoegd")}
 function savePerson(){if(!draft.title.trim())return;setData(d=>({...d,people:[{id:uid(),name:draft.title.trim(),birthday:draft.birthday,notes:draft.description},...d.people]}));setComposer(null);flash("Persoon toegevoegd")}
 function toggle(id:string){setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,done:!t.done}:t)}))}
 function TaskRow({t}:{t:Task}){return <div className={"task "+(t.done?"done":"")}><button className="check" onClick={()=>toggle(t.id)}>{t.done?"✓":""}</button><div><b>{t.title}</b><small>{t.area} · {t.priority}{t.date?" · "+t.date:" · Unscheduled"}</small></div><button className={"star "+(t.star?"on":"")} onClick={()=>setData(d=>({...d,tasks:d.tasks.map(x=>x.id===t.id?{...x,star:!x.star}:x)}))}>★</button></div>}
 if(!ready)return <main className="loading">Operations</main>;
 const nav=["Today","Inbox","Tasks","Routines","Projects","Areas","Notes","Resurfacing","People","Search","Settings"];
 return <div className="shell"><aside><div className="brand">Operations<small>PERSONAL OS</small></div>{nav.map(n=><button key={n} className={page===n?"active":""} onClick={()=>setPage(n)}>{n}{n==="Inbox"&&data.inbox.length?<em>{data.inbox.length}</em>:null}</button>)}<div className="hint">ALT + J · NEW TASK</div></aside><main><header><button onClick={()=>setPage("Inbox")}>Inbox {data.inbox.length}</button></header>
 {page==="Today"&&<><div className="todaytitle"><div><small>OVERVIEW</small><div className="todayline"><h1>Today</h1><span>{dateLabel}</span></div></div><span>{open.length} open tasks</span></div><Quick/><Section title="Top 3">{open.slice(0,3).map(t=><TaskRow key={t.id} t={t}/>)}</Section><div className="grid"><Section title="Next up">{open.slice(3,8).map(t=><TaskRow key={t.id} t={t}/>)}</Section><Section title="Notes"><div className="quote">{data.notes[0]?.text||"Nog geen notities."}</div><button className="textbtn" onClick={()=>openComposer("note")}>+ Add note</button></Section></div></>}
 {page==="Inbox"&&<><Title kicker="CAPTURE" title="Inbox" aside="Plan of bewaar later"/>{data.inbox.length?data.inbox.map((x,i)=><div className="review" key={i}><b>{x}</b><div><button onClick={()=>{setDraft(v=>({...v,title:x}));setProcessing(i);setComposer("task")}}>Inplannen</button><button className="ghost" onClick={()=>setData(d=>({...d,inbox:d.inbox.filter((_,j)=>j!==i)}))}>Verwijder</button></div></div>):<Empty text="Inbox is leeg."/ >}</>}
 {page==="Tasks"&&<><Title kicker="TASKS" title="Tasks" aside={data.tasks.length+" total"}/><button className="primary" onClick={()=>openComposer("task")}>+ Add task</button><Section title="Open">{open.map(t=><TaskRow key={t.id} t={t}/>)}</Section><Section title="Completed">{data.tasks.filter(t=>t.done).map(t=><TaskRow key={t.id} t={t}/>)}</Section></>}
 {page==="Routines"&&<><Title kicker="ROUTINES" title="Routines" aside="Daily habits"/><button className="primary" onClick={()=>openComposer("routine")}>+ Add routine</button>{["Morning","Afternoon","Evening"].map(part=><Section key={part} title={part}>{data.routines.filter(r=>r.part===part).map(r=><div className="routine" key={r.id}><button className="check" onClick={()=>setData(d=>({...d,routines:d.routines.map(x=>x.id===r.id?{...x,done:!x.done,streak:x.done?Math.max(0,x.streak-1):x.streak+1}:x)}))}>{r.done?"✓":""}</button><b>{r.title}</b><span>🔥 {r.streak}</span><button className="iconbtn" onClick={()=>setData(d=>({...d,routines:d.routines.filter(x=>x.id!==r.id)}))}>×</button></div>)}</Section>)}</>}
 {page==="Projects"&&<><Title kicker="PROJECTS" title="Projects" aside={data.projects.length+" active"}/><button className="primary" onClick={()=>openComposer("project")}>+ Add project</button><div className="cards">{data.projects.map(p=><div className="notecard" key={p.id}><small>{p.area}</small><h3>{p.title}</h3><p>{p.description||"No description"}</p><button className="textbtn" onClick={()=>setData(d=>({...d,projects:d.projects.filter(x=>x.id!==p.id)}))}>Delete</button></div>)}</div></>}
 {page==="Areas"&&<><Title kicker="SYSTEM" title="Areas" aside="editable"/><div className="cards">{data.areas.map((a,i)=><div className="card" key={a}><i/><b>{a}</b><div><button className="textbtn" onClick={()=>{const n=prompt("Nieuwe naam",a)?.trim();if(n)setData(d=>({...d,areas:d.areas.map((x,j)=>j===i?n:x),tasks:d.tasks.map(t=>t.area===a?{...t,area:n}:t),projects:d.projects.map(p=>p.area===a?{...p,area:n}:p)}))}}>Edit</button><button className="textbtn danger" onClick={()=>confirm("Area verwijderen?")&&setData(d=>({...d,areas:d.areas.filter((_,j)=>j!==i)}))}>Delete</button></div></div>)}<button className="addcard" onClick={()=>{const x=prompt("Nieuwe area")?.trim();if(x&&!data.areas.includes(x))setData(d=>({...d,areas:[...d.areas,x]}))}}>＋ Add area</button></div></>}
 {page==="Notes"&&<><Title kicker="LIBRARY" title="Notes" aside={data.notes.length+" saved"}/><button className="primary" onClick={()=>openComposer("note")}>+ Add note</button><div className="cards">{data.notes.map(n=><div className="notecard" key={n.id}><p>{n.text}</p><small>{new Date(n.created).toLocaleDateString("nl-NL")}</small><button className="textbtn danger" onClick={()=>setData(d=>({...d,notes:d.notes.filter(x=>x.id!==n.id)}))}>Delete</button></div>)}</div></>}
 {page==="Resurfacing"&&<><Title kicker="LIBRARY" title="Resurfacing" aside="one thought a day"/><div className="heroquote">“{data.notes.length?data.notes[new Date().getDate()%data.notes.length]?.text:"Nog niets opgeslagen."}”</div></>}
 {page==="People"&&<><Title kicker="CRM" title="People" aside={data.people.length+" people"}/><button className="primary" onClick={()=>openComposer("person")}>+ Add person</button><div className="cards">{data.people.map(p=><div className="notecard" key={p.id}><h3>{p.name}</h3>{p.birthday&&<small>Birthday · {p.birthday}</small>}<p>{p.notes}</p><button className="textbtn danger" onClick={()=>setData(d=>({...d,people:d.people.filter(x=>x.id!==p.id)}))}>Delete</button></div>)}</div></>}
 {page==="Search"&&<><Title kicker="FIND" title="Search" aside="everything"/><input className="searchbox" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks, notes, projects, people…"/>{search.trim()&&<div className="searchresults">{[...data.tasks.map(x=>({type:"Task",title:x.title})),...data.notes.map(x=>({type:"Note",title:x.text})),...data.projects.map(x=>({type:"Project",title:x.title})),...data.people.map(x=>({type:"Person",title:x.name}))].filter(x=>x.title.toLowerCase().includes(search.toLowerCase())).map((x,i)=><div className="result" key={i}><small>{x.type}</small><b>{x.title}</b></div>)}</div>}</>}
 {page==="Settings"&&<><Title kicker="SYSTEM" title="Settings" aside="local-first"/><div className="settings"><b>Storage</b><span>On this device · free</span><button onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="operations-backup.json";a.click()}}>Export backup</button></div></>}
 </main>{composer&&<Modal/>}{toast&&<div className="toast">{toast}</div>}</div>;
 function Quick(){return <div className="quick"><span>Quick add</span><button onClick={()=>openComposer("task")}>＋ Task</button><button onClick={()=>openComposer("note")}>＋ Note</button></div>}
 function Modal(){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget){setComposer(null);setProcessing(null)}}}><div className="modal"><div className="modalhead"><div><small>QUICK ADD</small><h2>{composer==="task"?"New task":composer==="note"?"New note":composer==="routine"?"New routine":composer==="project"?"New project":"New person"}</h2></div><button onClick={()=>{setComposer(null);setProcessing(null)}}>×</button></div>
 {composer==="note"?<textarea autoFocus value={draft.text} onChange={e=>setDraft(v=>({...v,text:e.target.value}))} placeholder="Schrijf je notitie…"/>:<><label>Name<input ref={inputRef} value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))} placeholder="Naam…"/></label>
 {composer==="task"&&<div className="formgrid"><label>Date<input type="date" value={draft.date} onChange={e=>setDraft(v=>({...v,date:e.target.value}))}/></label><label>Priority<select value={draft.priority} onChange={e=>setDraft(v=>({...v,priority:e.target.value as Priority}))}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Area<select value={draft.area} onChange={e=>setDraft(v=>({...v,area:e.target.value}))}>{data.areas.map(a=><option key={a}>{a}</option>)}</select></label></div>}
 {composer==="routine"&&<label>Moment<select value={draft.part} onChange={e=>setDraft(v=>({...v,part:e.target.value as Routine["part"]}))}><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label>}
 {composer==="project"&&<><label>Area<select value={draft.area} onChange={e=>setDraft(v=>({...v,area:e.target.value}))}>{data.areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Description<textarea value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))}/></label></>}
 {composer==="person"&&<><label>Birthday<input type="date" value={draft.birthday} onChange={e=>setDraft(v=>({...v,birthday:e.target.value}))}/></label><label>Notes<textarea value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))}/></label></>}</>}
 <div className="modalactions">{composer==="task"&&processing===null&&<button className="ghost" onClick={()=>saveTask(true)}>Naar Inbox</button>}<button className="primary" onClick={()=>composer==="task"?saveTask(false):composer==="note"?saveNote():composer==="routine"?saveRoutine():composer==="project"?saveProject():savePerson()}>{composer==="task"?"Direct inplannen":"Save"}</button></div></div></div>}
}
function Title({kicker,title,aside}:{kicker:string,title:string,aside:string}){return <div className="title"><div><small>{kicker}</small><h1>{title}</h1></div><span>{aside}</span></div>}
function Section({title,children}:{title:string,children:any}){return <section><div className="sectiontitle">{title}</div>{children}</section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
